enum Area {
  UNSELECTED,
  HOKKAIDO_1,
  HOKKAIDO_2,
  HOKKAIDO_3,
  HOKKAIDO_4,
  HOKKAIDO_5,
  HOKKAIDO_6,
  HOKKAIDO_7,
  HOKKAIDO_8,
  HOKKAIDO_9,
  HOKKAIDO_10,
  HOKKAIDO_11,
  HOKKAIDO_12,
  HOKKAIDO_13,
  HOKKAIDO_14,
  HOKKAIDO_15,
  HOKKAIDO_16,
  HOKKAIDO_17,
  AOMORI_1,
  AOMORI_2,
  AOMORI_3,
  AOMORI_4,
  AOMORI_5,
  AOMORI_6,
  IWATE_1,
  IWATE_2,
  IWATE_3,
  IWATE_4,
  IWATE_5,
  IWATE_6,
  IWATE_7,
  MIYAGI_1,
  MIYAGI_2,
  MIYAGI_3,
  MIYAGI_4,
  MIYAGI_5,
  MIYAGI_6,
  MIYAGI_7,
  MIYAGI_8,
  AKITA_1,
  AKITA_2,
  AKITA_3,
  AKITA_4,
  AKITA_5,
  AKITA_6,
  AKITA_7,
  AKITA_8,
  YAMAGATA_1,
  YAMAGATA_2,
  YAMAGATA_3,
  YAMAGATA_4,
  YAMAGATA_5,
  YAMAGATA_6,
  YAMAGATA_7,
  FUKUSHIMA_1,
  FUKUSHIMA_2,
  FUKUSHIMA_3,
  FUKUSHIMA_4,
  FUKUSHIMA_5,
  FUKUSHIMA_6,
  FUKUSHIMA_7,
  FUKUSHIMA_8,
  FUKUSHIMA_9,
  FUKUSHIMA_10,
  IBARAKI_1,
  IBARAKI_2,
  IBARAKI_3,
  IBARAKI_4,
  IBARAKI_5,
  IBARAKI_6,
  IBARAKI_7,
  IBARAKI_8,
  IBARAKI_9,
  TOCHIGI_1,
  TOCHIGI_2,
  TOCHIGI_3,
  TOCHIGI_4,
  TOCHIGI_5,
  TOCHIGI_6,
  TOCHIGI_7,
  GUNMA_1,
  GUNMA_2,
  GUNMA_3,
  GUNMA_4,
  GUNMA_5,
  GUNMA_6,
  GUNMA_7,
  GUNMA_8,
  GUNMA_9,
  SAITAMA_1,
  SAITAMA_2,
  SAITAMA_3,
  SAITAMA_4,
  SAITAMA_5,
  SAITAMA_6,
  SAITAMA_7,
  SAITAMA_8,
  SAITAMA_9,
  SAITAMA_10,
  SAITAMA_11,
  SAITAMA_12,
  SAITAMA_13,
  SAITAMA_14,
  SAITAMA_15,
  SAITAMA_16,
  SAITAMA_17,
  SAITAMA_18,
  SAITAMA_19,
  SAITAMA_20,
  SAITAMA_21,
  SAITAMA_22,
  SAITAMA_23,
  CHIBA_1,
  CHIBA_2,
  CHIBA_3,
  CHIBA_4,
  CHIBA_5,
  CHIBA_6,
  CHIBA_7,
  CHIBA_8,
  CHIBA_9,
  CHIBA_10,
  CHIBA_11,
  CHIBA_12,
  CHIBA_13,
  CHIBA_14,
  CHIBA_15,
  CHIBA_16,
  CHIBA_17,
  CHIBA_18,
  CHIBA_19,
  CHIBA_20,
  CHIBA_21,
  CHIBA_22,
  CHIBA_23,
  TOKYO_1,
  TOKYO_2,
  TOKYO_3,
  TOKYO_4,
  TOKYO_5,
  TOKYO_6,
  TOKYO_7,
  TOKYO_8,
  TOKYO_9,
  TOKYO_10,
  TOKYO_11,
  TOKYO_12,
  TOKYO_13,
  TOKYO_14,
  TOKYO_15,
  TOKYO_16,
  TOKYO_17,
  TOKYO_18,
  TOKYO_19,
  TOKYO_20,
  TOKYO_21,
  TOKYO_22,
  TOKYO_23,
  TOKYO_24,
  TOKYO_25,
  TOKYO_26,
  TOKYO_27,
  TOKYO_28,
  TOKYO_29,
  TOKYO_30,
  TOKYO_31,
  TOKYO_32,
  TOKYO_33,
  TOKYO_34,
  KANAGAWA_1,
  KANAGAWA_2,
  KANAGAWA_3,
  KANAGAWA_4,
  KANAGAWA_5,
  KANAGAWA_6,
  KANAGAWA_7,
  KANAGAWA_8,
  KANAGAWA_9,
  KANAGAWA_10,
  KANAGAWA_11,
  KANAGAWA_12,
  KANAGAWA_13,
  KANAGAWA_14,
  KANAGAWA_15,
  KANAGAWA_16,
  KANAGAWA_17,
  KANAGAWA_18,
  KANAGAWA_19,
  KANAGAWA_20,
  KANAGAWA_21,
  KANAGAWA_22,
  KANAGAWA_23,
  NIIGATA_1,
  NIIGATA_2,
  NIIGATA_3,
  NIIGATA_4,
  NIIGATA_5,
  NIIGATA_6,
  NIIGATA_7,
  TOYAMA_1,
  TOYAMA_2,
  TOYAMA_3,
  TOYAMA_4,
  TOYAMA_5,
  TOYAMA_6,
  TOYAMA_7,
  ISHIKAWA_1,
  ISHIKAWA_2,
  ISHIKAWA_3,
  ISHIKAWA_4,
  ISHIKAWA_5,
  ISHIKAWA_6,
  FUKUI_1,
  FUKUI_2,
  FUKUI_3,
  FUKUI_4,
  FUKUI_5,
  FUKUI_6,
  YAMANASHI_1,
  YAMANASHI_2,
  YAMANASHI_3,
  YAMANASHI_4,
  YAMANASHI_5,
  YAMANASHI_6,
  YAMANASHI_7,
  NAGANO_1,
  NAGANO_2,
  NAGANO_3,
  NAGANO_4,
  NAGANO_5,
  NAGANO_6,
  NAGANO_7,
  NAGANO_8,
  NAGANO_9,
  GIFU_1,
  GIFU_2,
  GIFU_3,
  GIFU_4,
  GIFU_5,
  GIFU_6,
  SHIZUOKA_1,
  SHIZUOKA_2,
  SHIZUOKA_3,
  SHIZUOKA_4,
  SHIZUOKA_5,
  SHIZUOKA_6,
  SHIZUOKA_7,
  SHIZUOKA_8,
  AICHI_1,
  AICHI_2,
  AICHI_3,
  AICHI_4,
  AICHI_5,
  AICHI_6,
  AICHI_7,
  AICHI_8,
  AICHI_9,
  AICHI_10,
  AICHI_11,
  AICHI_12,
  AICHI_13,
  AICHI_14,
  AICHI_15,
  AICHI_16,
  AICHI_17,
  MIE_1,
  MIE_2,
  MIE_3,
  MIE_4,
  MIE_5,
  MIE_6,
  MIE_7,
  MIE_8,
  MIE_9,
  MIE_10,
  MIE_11,
  MIE_12,
  MIE_13,
  MIE_14,
  MIE_15,
  MIE_16,
  MIE_17,
  MIE_18,
  MIE_19,
  MIE_20,
  MIE_21,
  MIE_22,
  MIE_23,
  MIE_24,
  MIE_25,
  MIE_26,
  MIE_27,
  MIE_28,
  MIE_29,
  MIE_30,
  MIE_31,
  SHIGA_1,
  SHIGA_2,
  SHIGA_3,
  SHIGA_4,
  SHIGA_5,
  SHIGA_6,
  SHIGA_7,
  KYOTO_1,
  KYOTO_2,
  KYOTO_3,
  KYOTO_4,
  KYOTO_5,
  KYOTO_6,
  KYOTO_7,
  KYOTO_8,
  KYOTO_9,
  KYOTO_10,
  KYOTO_11,
  KYOTO_12,
  KYOTO_13,
  OSAKA_1,
  OSAKA_2,
  OSAKA_3,
  OSAKA_4,
  OSAKA_5,
  OSAKA_6,
  OSAKA_7,
  OSAKA_8,
  OSAKA_9,
  OSAKA_10,
  OSAKA_11,
  OSAKA_12,
  OSAKA_13,
  OSAKA_14,
  OSAKA_15,
  OSAKA_16,
  OSAKA_17,
  OSAKA_18,
  OSAKA_19,
  OSAKA_20,
  OSAKA_21,
  OSAKA_22,
  OSAKA_23,
  OSAKA_24,
  OSAKA_25,
  OSAKA_26,
  OSAKA_27,
  OSAKA_28,
  OSAKA_29,
  HYOGO_1,
  HYOGO_2,
  HYOGO_3,
  HYOGO_4,
  HYOGO_5,
  HYOGO_6,
  HYOGO_7,
  HYOGO_8,
  HYOGO_9,
  HYOGO_10,
  HYOGO_11,
  HYOGO_12,
  NARA_1,
  NARA_2,
  NARA_3,
  NARA_4,
  NARA_5,
  NARA_6,
  NARA_7,
  NARA_8,
  WAKAYAMA_1,
  WAKAYAMA_2,
  WAKAYAMA_3,
  WAKAYAMA_4,
  WAKAYAMA_5,
  WAKAYAMA_6,
  WAKAYAMA_7,
  TOTTORI_1,
  TOTTORI_2,
  TOTTORI_3,
  TOTTORI_4,
  TOTTORI_5,
  SHIMANE_1,
  SHIMANE_2,
  SHIMANE_3,
  SHIMANE_4,
  SHIMANE_5,
  SHIMANE_6,
  OKAYAMA_1,
  OKAYAMA_2,
  OKAYAMA_3,
  OKAYAMA_4,
  OKAYAMA_5,
  OKAYAMA_6,
  OKAYAMA_7,
  HIROSHIMA_1,
  HIROSHIMA_2,
  HIROSHIMA_3,
  HIROSHIMA_4,
  HIROSHIMA_5,
  HIROSHIMA_6,
  HIROSHIMA_7,
  HIROSHIMA_8,
  HIROSHIMA_9,
  HIROSHIMA_10,
  HIROSHIMA_11,
  YAMAGUCHI_1,
  YAMAGUCHI_2,
  YAMAGUCHI_3,
  YAMAGUCHI_4,
  YAMAGUCHI_5,
  YAMAGUCHI_6,
  YAMAGUCHI_7,
  YAMAGUCHI_8,
  TOKUSHIMA_1,
  TOKUSHIMA_2,
  TOKUSHIMA_3,
  TOKUSHIMA_4,
  TOKUSHIMA_5,
  TOKUSHIMA_6,
  KAGAWA_1,
  KAGAWA_2,
  KAGAWA_3,
  KAGAWA_4,
  KAGAWA_5,
  KAGAWA_6,
  EHIME_1,
  EHIME_2,
  EHIME_3,
  EHIME_4,
  EHIME_5,
  EHIME_6,
  KOCHI_1,
  KOCHI_2,
  KOCHI_3,
  KOCHI_4,
  KOCHI_5,
  KOCHI_6,
  FUKUOKA_1,
  FUKUOKA_2,
  FUKUOKA_3,
  FUKUOKA_4,
  FUKUOKA_5,
  FUKUOKA_6,
  FUKUOKA_7,
  FUKUOKA_8,
  FUKUOKA_9,
  FUKUOKA_10,
  FUKUOKA_11,
  FUKUOKA_12,
  FUKUOKA_13,
  FUKUOKA_14,
  FUKUOKA_15,
  FUKUOKA_16,
  FUKUOKA_17,
  SAGA_1,
  SAGA_2,
  SAGA_3,
  SAGA_4,
  SAGA_5,
  SAGA_6,
  NAGASAKI_1,
  NAGASAKI_2,
  NAGASAKI_3,
  NAGASAKI_4,
  NAGASAKI_5,
  NAGASAKI_6,
  NAGASAKI_7,
  KUMAMOTO_1,
  KUMAMOTO_2,
  KUMAMOTO_3,
  KUMAMOTO_4,
  KUMAMOTO_5,
  KUMAMOTO_6,
  KUMAMOTO_7,
  OITA_1,
  OITA_2,
  OITA_3,
  OITA_4,
  OITA_5,
  OITA_6,
  MIYAZAKI_1,
  MIYAZAKI_2,
  MIYAZAKI_3,
  MIYAZAKI_4,
  MIYAZAKI_5,
  MIYAZAKI_6,
  MIYAZAKI_7,
  KAGOSHIMA_1,
  KAGOSHIMA_2,
  KAGOSHIMA_3,
  KAGOSHIMA_4,
  KAGOSHIMA_5,
  KAGOSHIMA_6,
  OKINAWA_1,
  OKINAWA_2,
  OKINAWA_3,
  OKINAWA_4,
  OKINAWA_5,
  OKINAWA_6,
}

extension AreaHelper on Area {
  static const names = {
    Area.UNSELECTED: '未選択',
    Area.HOKKAIDO_1: '北海道すべて',
    Area.HOKKAIDO_2: '札幌駅周辺',
    Area.HOKKAIDO_3: '北区・東区',
    Area.HOKKAIDO_4: '大通',
    Area.HOKKAIDO_5: '豊平区・南区',
    Area.HOKKAIDO_6: '西区・手稲区・小樽市',
    Area.HOKKAIDO_7: '円山周辺',
    Area.HOKKAIDO_8: '白石区・厚別区・清田区',
    Area.HOKKAIDO_9: 'すすきの・市電沿線',
    Area.HOKKAIDO_10: '函館',
    Area.HOKKAIDO_11: '千歳・恵庭・江別',
    Area.HOKKAIDO_12: '室蘭・登別・苫小牧',
    Area.HOKKAIDO_13: '旭川・滝川',
    Area.HOKKAIDO_14: '網走・北見',
    Area.HOKKAIDO_15: '釧路・根室',
    Area.HOKKAIDO_16: '帯広・十勝',
    Area.HOKKAIDO_17: '北海道その他',
    Area.AOMORI_1: '青森県すべて',
    Area.AOMORI_2: '青森',
    Area.AOMORI_3: '弘前・黒石',
    Area.AOMORI_4: '八戸・三沢',
    Area.AOMORI_5: 'むつ・下北半島',
    Area.AOMORI_6: '西津軽・北津軽・五所川原',
    Area.IWATE_1: '岩手県すべて',
    Area.IWATE_2: '盛岡',
    Area.IWATE_3: '花巻・北上・遠野',
    Area.IWATE_4: '一関・平泉',
    Area.IWATE_5: '奥州',
    Area.IWATE_6: '八幡平・二戸',
    Area.IWATE_7: '岩手県その他',
    Area.MIYAGI_1: '宮城県すべて',
    Area.MIYAGI_2: '仙台駅周辺・一番町・国分町',
    Area.MIYAGI_3: '北四番町・その他青葉区',
    Area.MIYAGI_4: '泉区・富谷',
    Area.MIYAGI_5: '宮城野区・若林区・利府・多賀城',
    Area.MIYAGI_6: '太白区・名取・岩沼',
    Area.MIYAGI_7: '大崎・登米・栗原',
    Area.MIYAGI_8: '宮城県その他',
    Area.AKITA_1: '秋田県すべて',
    Area.AKITA_2: '秋田',
    Area.AKITA_3: '大館・鹿角',
    Area.AKITA_4: '横手・湯沢',
    Area.AKITA_5: '能代・男鹿・八郎潟',
    Area.AKITA_6: '田沢湖・角館・大曲',
    Area.AKITA_7: '由利本荘',
    Area.AKITA_8: '秋田県その他',
    Area.YAMAGATA_1: '山形県すべて',
    Area.YAMAGATA_2: '山形',
    Area.YAMAGATA_3: '上山・米沢',
    Area.YAMAGATA_4: '新庄・尾花沢',
    Area.YAMAGATA_5: '天童・寒河江・東根',
    Area.YAMAGATA_6: '酒田・鶴岡',
    Area.YAMAGATA_7: '山形県その他',
    Area.FUKUSHIMA_1: '福島県すべて',
    Area.FUKUSHIMA_2: '福島',
    Area.FUKUSHIMA_3: '郡山',
    Area.FUKUSHIMA_4: '白河',
    Area.FUKUSHIMA_5: 'いわき',
    Area.FUKUSHIMA_6: '会津若松',
    Area.FUKUSHIMA_7: '喜多方',
    Area.FUKUSHIMA_8: '相馬',
    Area.FUKUSHIMA_9: '南会津',
    Area.FUKUSHIMA_10: '福島県その他',
    Area.IBARAKI_1: '茨城県すべて',
    Area.IBARAKI_2: '水戸',
    Area.IBARAKI_3: 'つくば・土浦・石岡',
    Area.IBARAKI_4: '守谷・取手',
    Area.IBARAKI_5: '牛久・龍ケ崎',
    Area.IBARAKI_6: '鹿嶋・水郷周辺',
    Area.IBARAKI_7: '北茨城・日立・ひたちなか',
    Area.IBARAKI_8: '古河・常総・筑西',
    Area.IBARAKI_9: '茨城県その他',
    Area.TOCHIGI_1: '栃木県すべて',
    Area.TOCHIGI_2: '宇都宮',
    Area.TOCHIGI_3: '栃木・佐野・足利',
    Area.TOCHIGI_4: '真岡・下野・小山',
    Area.TOCHIGI_5: '日光・鹿沼',
    Area.TOCHIGI_6: '太田原・那須・矢坂',
    Area.TOCHIGI_7: '栃木県その他',
    Area.GUNMA_1: '群馬県すべて',
    Area.GUNMA_2: '高崎',
    Area.GUNMA_3: '前橋',
    Area.GUNMA_4: '桐生・相老・相生',
    Area.GUNMA_5: '伊勢崎・新伊勢崎',
    Area.GUNMA_6: '太田・館林',
    Area.GUNMA_7: '富岡・藤岡・安中',
    Area.GUNMA_8: '渋川・沼田店・みなかみ',
    Area.GUNMA_9: '群馬県その他',
    Area.SAITAMA_1: '埼玉県すべて',
    Area.SAITAMA_2: '大宮',
    Area.SAITAMA_3: '与野',
    Area.SAITAMA_4: '越谷',
    Area.SAITAMA_5: '草加・八潮・三郷・吉川',
    Area.SAITAMA_6: '川口・蕨',
    Area.SAITAMA_7: '戸田',
    Area.SAITAMA_8: '川越・本川越',
    Area.SAITAMA_9: 'ふじみ野・鶴瀬・上福岡',
    Area.SAITAMA_10: '浦和',
    Area.SAITAMA_11: '狭山市・入間',
    Area.SAITAMA_12: '所沢・小手指',
    Area.SAITAMA_13: '飯能・東飯能',
    Area.SAITAMA_14: '春日部・岩槻',
    Area.SAITAMA_15: '熊谷・行田',
    Area.SAITAMA_16: '坂戸・若葉・鶴ヶ島',
    Area.SAITAMA_17: '上尾・桶川・鴻巣',
    Area.SAITAMA_18: '久喜・幸手・蓮田',
    Area.SAITAMA_19: '朝霞・志木・和光',
    Area.SAITAMA_20: '深谷・本庄・神保原',
    Area.SAITAMA_21: '東松山・武蔵嵐山・高坂',
    Area.SAITAMA_22: '羽生・加須',
    Area.SAITAMA_23: '毛呂・越生',
    Area.CHIBA_1: '千葉県すべて',
    Area.CHIBA_2: '千葉・千葉中央・西千葉',
    Area.CHIBA_3: '柏・南柏',
    Area.CHIBA_4: '松戸・新松戸・新八柱',
    Area.CHIBA_5: '船橋・西船橋',
    Area.CHIBA_6: '浦安・行徳・妙典',
    Area.CHIBA_7: '市川・本八幡・下総中山',
    Area.CHIBA_8: '津田沼・京成津田沼',
    Area.CHIBA_9: '北習志野・習志野',
    Area.CHIBA_10: '八千代台・勝田台',
    Area.CHIBA_11: '蘇我・鎌取・土気',
    Area.CHIBA_12: '四街道・都賀',
    Area.CHIBA_13: '木更津・君津',
    Area.CHIBA_14: '八幡宿・五井・姉ヶ崎',
    Area.CHIBA_15: '成田・佐倉・ユーカリが丘',
    Area.CHIBA_16: '銚子・旭',
    Area.CHIBA_17: '茂原・東金・成東',
    Area.CHIBA_18: '稲毛・稲毛海岸',
    Area.CHIBA_19: '幕張本郷・新検見川',
    Area.CHIBA_20: '流山・南流山・江戸川台',
    Area.CHIBA_21: '我孫子',
    Area.CHIBA_22: '鎌ヶ谷・西白井',
    Area.CHIBA_23: '館山・鴨川・南房総',
    Area.TOKYO_1: '東京都すべて',
    Area.TOKYO_2: '渋谷',
    Area.TOKYO_3: '原宿',
    Area.TOKYO_4: '表参道・青山',
    Area.TOKYO_5: '新宿',
    Area.TOKYO_6: '池袋',
    Area.TOKYO_7: '銀座・新橋・有楽町',
    Area.TOKYO_8: '恵比寿・代官山・中目黒',
    Area.TOKYO_9: '自由が丘・学芸大学',
    Area.TOKYO_10: '六本木・麻布十番',
    Area.TOKYO_11: '三軒茶屋・用賀・二子玉川',
    Area.TOKYO_12: '下北沢・代々木上原',
    Area.TOKYO_13: '目黒・戸越・武蔵小山',
    Area.TOKYO_14: '北千住・町屋・亀有',
    Area.TOKYO_15: '錦糸町・小岩・青砥',
    Area.TOKYO_16: '吉祥寺・荻窪・三鷹',
    Area.TOKYO_17: '立川・国立・国分寺',
    Area.TOKYO_18: '八王子・日野・昭島',
    Area.TOKYO_19: '中野・高円寺・阿佐ヶ谷',
    Area.TOKYO_20: '品川・大森・蒲田',
    Area.TOKYO_21: '上野・日本橋・浅草',
    Area.TOKYO_22: '日暮里・駒込・千駄木',
    Area.TOKYO_23: '赤羽・十条・王子',
    Area.TOKYO_24: '葛西・西葛西・門前仲町',
    Area.TOKYO_25: '経堂・成城学園・狛江',
    Area.TOKYO_26: '飯田橋・四谷・御茶ノ水',
    Area.TOKYO_27: '笹塚・下高井戸・千歳烏山',
    Area.TOKYO_28: '町田',
    Area.TOKYO_29: '板橋・成増・巣鴨',
    Area.TOKYO_30: '田無・小平・久米川',
    Area.TOKYO_31: '大泉学園・江古田・練馬',
    Area.TOKYO_32: '東久留米・ひばりヶ丘',
    Area.TOKYO_33: '調布・府中',
    Area.TOKYO_34: '多摩・聖蹟桜ヶ丘・稲城',
    Area.KANAGAWA_1: '神奈川県すべて',
    Area.KANAGAWA_2: '横浜',
    Area.KANAGAWA_3: '川崎',
    Area.KANAGAWA_4: '鶴見',
    Area.KANAGAWA_5: '溝の口・武蔵溝ノ口・高津',
    Area.KANAGAWA_6: 'たまプラーザ・あざみ野',
    Area.KANAGAWA_7: '本厚木・海老名・伊勢原',
    Area.KANAGAWA_8: '港北・都筑・青葉台',
    Area.KANAGAWA_9: '横須賀・鎌倉・逗子',
    Area.KANAGAWA_10: '桜木町・みなとみらい・関内',
    Area.KANAGAWA_11: '橋本・相模原・淵野辺',
    Area.KANAGAWA_12: '大船・戸塚・保土ヶ谷',
    Area.KANAGAWA_13: '藤沢・湘南台・江ノ島',
    Area.KANAGAWA_14: '武蔵小杉・日吉・綱島',
    Area.KANAGAWA_15: '相模大野・小田急相模原',
    Area.KANAGAWA_16: '東林間・中央林間・南林間',
    Area.KANAGAWA_17: '大和・さがみ野・二俣川',
    Area.KANAGAWA_18: '上大岡・金沢文庫・港南台',
    Area.KANAGAWA_19: '新横浜・菊名・東神奈川',
    Area.KANAGAWA_20: '新百合ヶ丘・登戸・稲田堤',
    Area.KANAGAWA_21: '茅ヶ崎・辻堂・平塚',
    Area.KANAGAWA_22: '元町・石川町',
    Area.KANAGAWA_23: '小田原・鴨宮・国府津',
    Area.NIIGATA_1: '新潟県すべて',
    Area.NIIGATA_2: '新潟・三条',
    Area.NIIGATA_3: '長岡・柏崎',
    Area.NIIGATA_4: '上越・糸魚川・妙高',
    Area.NIIGATA_5: '魚沼・十日町・湯沢',
    Area.NIIGATA_6: '五泉・新発田・村上',
    Area.NIIGATA_7: '新潟県その他',
    Area.TOYAMA_1: '富山県すべて',
    Area.TOYAMA_2: '富山',
    Area.TOYAMA_3: '黒部・魚津・滑川',
    Area.TOYAMA_4: '砺波・射水',
    Area.TOYAMA_5: '高岡・氷見',
    Area.TOYAMA_6: '小矢部・南砺',
    Area.TOYAMA_7: '富山県その他',
    Area.ISHIKAWA_1: '石川県すべて',
    Area.ISHIKAWA_2: '金沢・野々市',
    Area.ISHIKAWA_3: '白山・小松・加賀',
    Area.ISHIKAWA_4: '能登南部',
    Area.ISHIKAWA_5: '能登北部',
    Area.ISHIKAWA_6: '石川県その他',
    Area.FUKUI_1: '福井県すべて',
    Area.FUKUI_2: '福井・坂井',
    Area.FUKUI_3: '越前・鯖江',
    Area.FUKUI_4: '敦賀・小浜',
    Area.FUKUI_5: '大野・勝山',
    Area.FUKUI_6: '福井県その他',
    Area.YAMANASHI_1: '山梨県すべて',
    Area.YAMANASHI_2: '甲府・山梨・笛吹',
    Area.YAMANASHI_3: '北杜・韮崎・南アルプス',
    Area.YAMANASHI_4: '富士吉田・都留',
    Area.YAMANASHI_5: '甲斐・中巨摩・中央',
    Area.YAMANASHI_6: '大月・上野原',
    Area.YAMANASHI_7: '山梨県その他',
    Area.NAGANO_1: '長野県すべて',
    Area.NAGANO_2: '長野・千曲',
    Area.NAGANO_3: '松本・塩尻',
    Area.NAGANO_4: '飯山・中野・須坂',
    Area.NAGANO_5: '軽井沢・佐久',
    Area.NAGANO_6: '上田・小諸・東御',
    Area.NAGANO_7: '安曇野・大町',
    Area.NAGANO_8: '駒ヶ根・飯田・伊那',
    Area.NAGANO_9: '茅野・諏訪',
    Area.GIFU_1: '岐阜県すべて',
    Area.GIFU_2: '岐阜市・大垣・羽島',
    Area.GIFU_3: '美濃加茂・関・各務原',
    Area.GIFU_4: '可児・多治見・中津川',
    Area.GIFU_5: '高山・飛騨・下呂',
    Area.GIFU_6: '岐阜県その他',
    Area.SHIZUOKA_1: '静岡県すべて',
    Area.SHIZUOKA_2: '静岡・清水',
    Area.SHIZUOKA_3: '浜松',
    Area.SHIZUOKA_4: '磐田・袋井・掛川',
    Area.SHIZUOKA_5: '焼津・藤枝・牧之原',
    Area.SHIZUOKA_6: '沼津・富士・御殿場',
    Area.SHIZUOKA_7: '熱海・三島・伊豆',
    Area.SHIZUOKA_8: '静岡県その他',
    Area.AICHI_1: '愛知県すべて',
    Area.AICHI_2: '栄・矢場町・久屋大通',
    Area.AICHI_3: '名駅周辺・中村公園・西区',
    Area.AICHI_4: '大須・金山・熱田区',
    Area.AICHI_5: '千種・名東・藤が丘',
    Area.AICHI_6: '御器所・八事・赤池',
    Area.AICHI_7: '大曽根・守山・尾張旭・瀬戸',
    Area.AICHI_8: '新瑞橋・野並・緑区',
    Area.AICHI_9: '南区・港区・中川区',
    Area.AICHI_10: '豊田・岡崎・西尾',
    Area.AICHI_11: '春日井・小牧・犬山',
    Area.AICHI_12: '日進・長久手・みよし',
    Area.AICHI_13: '一宮・稲沢・清洲',
    Area.AICHI_14: '大府・東海市・豊明',
    Area.AICHI_15: '刈谷・安城・知立',
    Area.AICHI_16: '豊橋・豊川・田原',
    Area.AICHI_17: '知多・半田・常滑',
    Area.MIE_1: '三重県すべて',
    Area.MIE_2: '四日市:富洲原地区',
    Area.MIE_3: '四日市:富田地区',
    Area.MIE_4: '四日市:大矢知地区',
    Area.MIE_5: '四日市:八郷地区',
    Area.MIE_6: '四日市:下野地区',
    Area.MIE_7: '四日市:保々地区',
    Area.MIE_8: '四日市:羽津地区',
    Area.MIE_9: '四日市:橋北地区',
    Area.MIE_10: '四日市:海蔵地区',
    Area.MIE_11: '四日市:三重地区',
    Area.MIE_12: '四日市:県地区',
    Area.MIE_13: '四日市:神前地区',
    Area.MIE_14: '四日市:川島地区',
    Area.MIE_15: '四日市:桜地地区',
    Area.MIE_16: '四日市:常磐地区',
    Area.MIE_17: '四日市:四郷地区',
    Area.MIE_18: '四日市:小山田地区',
    Area.MIE_19: '四日市:水沢地区',
    Area.MIE_20: '四日市:塩浜地区',
    Area.MIE_21: '四日市:日永地区',
    Area.MIE_22: '四日市:河原地区',
    Area.MIE_23: '四日市:楠池地区',
    Area.MIE_24: '津・鈴鹿',
    Area.MIE_25: '朝日町',
    Area.MIE_26: '桑名',
    Area.MIE_27: '松阪',
    Area.MIE_28: '伊勢・志摩・玉城町',
    Area.MIE_29: '伊賀・名張',
    Area.MIE_30: '熊野・尾鷲',
    Area.MIE_31: '三重県その他',
    Area.SHIGA_1: '滋賀県すべて',
    Area.SHIGA_2: '大津・草津',
    Area.SHIGA_3: '甲賀・湖南・栗東',
    Area.SHIGA_4: '湖東（近江・彦根・守山）',
    Area.SHIGA_5: '湖北（長浜・米原・余呉）',
    Area.SHIGA_6: '湖西（高島・マキノ）',
    Area.SHIGA_7: '滋賀県その他',
    Area.KYOTO_1: '京都府すべて',
    Area.KYOTO_2: '四条烏丸・御池・丸太町',
    Area.KYOTO_3: '四条河原町・河原町三条',
    Area.KYOTO_4: '京都駅・烏丸五条',
    Area.KYOTO_5: '四条大宮・西院・二条駅',
    Area.KYOTO_6: '桂・花園・嵐山',
    Area.KYOTO_7: '上京区・左京区・北区',
    Area.KYOTO_8: '山科・東山',
    Area.KYOTO_9: '南区・伏見',
    Area.KYOTO_10: '長岡京市・向日市・八幡',
    Area.KYOTO_11: '宇治・京田辺・城陽',
    Area.KYOTO_12: '亀岡・福知山・舞鶴',
    Area.KYOTO_13: '木津・精華町',
    Area.OSAKA_1: '大阪府すべて',
    Area.OSAKA_2: '梅田・茶屋町',
    Area.OSAKA_3: '心斎橋・南船場・アメ村',
    Area.OSAKA_4: '堀江・四ツ橋・新町',
    Area.OSAKA_5: 'なんば・日本橋',
    Area.OSAKA_6: '天王寺区・阿倍野区',
    Area.OSAKA_7: '福島区・野田',
    Area.OSAKA_8: '淀屋橋・本町・肥後橋',
    Area.OSAKA_9: '天神橋・天満',
    Area.OSAKA_10: '谷町・上本町・玉造',
    Area.OSAKA_11: '淡路・上新庄',
    Area.OSAKA_12: '東三国・十三・淀川区',
    Area.OSAKA_13: '京橋・都島区',
    Area.OSAKA_14: '鶴見区・城東区・旭区',
    Area.OSAKA_15: '東成区・生野区',
    Area.OSAKA_16: '住吉区・住之江区・西成区',
    Area.OSAKA_17: '平野区・東住吉区',
    Area.OSAKA_18: '大正・九条・弁天町',
    Area.OSAKA_19: '吹田・江坂',
    Area.OSAKA_20: '池田・豊中・箕面',
    Area.OSAKA_21: '守口・門真・大東',
    Area.OSAKA_22: '枚方・寝屋川・交野',
    Area.OSAKA_23: '高槻・茨木・摂津',
    Area.OSAKA_24: '東大阪・八尾・柏原',
    Area.OSAKA_25: '松原・藤井寺・羽曳野',
    Area.OSAKA_26: '堺・中百舌鳥',
    Area.OSAKA_27: '狭山・河内長野・富田林',
    Area.OSAKA_28: '泉大津・和泉・岸和田',
    Area.OSAKA_29: '泉佐野・泉南・阪南',
    Area.HYOGO_1: '兵庫県すべて',
    Area.HYOGO_2: '三宮・元町',
    Area.HYOGO_3: '尼崎・塚口・武庫之荘',
    Area.HYOGO_4: '宝塚・川西・伊丹',
    Area.HYOGO_5: '西宮・芦屋',
    Area.HYOGO_6: '灘区・東灘区・岡本',
    Area.HYOGO_7: '神戸・兵庫区・長田区',
    Area.HYOGO_8: '須磨区・垂水区・西区',
    Area.HYOGO_9: '三田・北区',
    Area.HYOGO_10: '明石・加古川・三木',
    Area.HYOGO_11: '姫路・播州赤穂',
    Area.HYOGO_12: '兵庫県その他',
    Area.NARA_1: '奈良県すべて',
    Area.NARA_2: '奈良・西大寺・高の原',
    Area.NARA_3: '生駒・学園前・登美が丘',
    Area.NARA_4: '大和郡山・天理',
    Area.NARA_5: '橿原・桜井',
    Area.NARA_6: '大和高田・香芝',
    Area.NARA_7: '五條・御所・葛城',
    Area.NARA_8: '奈良県その他',
    Area.WAKAYAMA_1: '和歌山県すべて',
    Area.WAKAYAMA_2: '和歌山市・岩出',
    Area.WAKAYAMA_3: '海南・有田',
    Area.WAKAYAMA_4: '御坊',
    Area.WAKAYAMA_5: '田辺・白浜',
    Area.WAKAYAMA_6: '新宮',
    Area.WAKAYAMA_7: '和歌山県その他',
    Area.TOTTORI_1: '鳥取県すべて',
    Area.TOTTORI_2: '鳥取市',
    Area.TOTTORI_3: '倉吉・三朝',
    Area.TOTTORI_4: '米子・境港・大山',
    Area.TOTTORI_5: '鳥取県その他',
    Area.SHIMANE_1: '島根県すべて',
    Area.SHIMANE_2: '松江・安来',
    Area.SHIMANE_3: '出雲・雲南',
    Area.SHIMANE_4: '浜田・江津・大田',
    Area.SHIMANE_5: '益田・津和野',
    Area.SHIMANE_6: '島根県その他',
    Area.OKAYAMA_1: '岡山県すべて',
    Area.OKAYAMA_2: '岡山・玉野',
    Area.OKAYAMA_3: '倉敷・笠岡・井原',
    Area.OKAYAMA_4: '総社・高梁・新見',
    Area.OKAYAMA_5: '津山・真庭・美作',
    Area.OKAYAMA_6: '備前・赤磐',
    Area.OKAYAMA_7: '岡山県その他',
    Area.HIROSHIMA_1: '広島県すべて',
    Area.HIROSHIMA_2: '八丁堀・紙屋町',
    Area.HIROSHIMA_3: '段原・皆実町・宇品',
    Area.HIROSHIMA_4: '広島駅周辺・府中町・安芸区',
    Area.HIROSHIMA_5: '横川・舟入・西広島',
    Area.HIROSHIMA_6: '井口・五日市・廿日市',
    Area.HIROSHIMA_7: '安佐南区・安佐北区',
    Area.HIROSHIMA_8: '福山・尾道・三原',
    Area.HIROSHIMA_9: '呉・竹原・東広島',
    Area.HIROSHIMA_10: '三次・庄原',
    Area.HIROSHIMA_11: '広島県その他',
    Area.YAMAGUCHI_1: '山口県すべて',
    Area.YAMAGUCHI_2: '山口・防府',
    Area.YAMAGUCHI_3: '下関',
    Area.YAMAGUCHI_4: '萩・長門',
    Area.YAMAGUCHI_5: '宇部・小野田',
    Area.YAMAGUCHI_6: '周南・下松・光',
    Area.YAMAGUCHI_7: '岩国・柳井',
    Area.YAMAGUCHI_8: '山口県その他',
    Area.TOKUSHIMA_1: '徳島県すべて',
    Area.TOKUSHIMA_2: '徳島・鳴門',
    Area.TOKUSHIMA_3: '阿南・小松島',
    Area.TOKUSHIMA_4: '阿波・吉野川',
    Area.TOKUSHIMA_5: '美馬・三好',
    Area.TOKUSHIMA_6: '徳島県その他',
    Area.KAGAWA_1: '香川県すべて',
    Area.KAGAWA_2: '高松市',
    Area.KAGAWA_3: '坂出・丸亀・善通寺',
    Area.KAGAWA_4: '観音寺・三豊',
    Area.KAGAWA_5: 'さぬき・東かがわ',
    Area.KAGAWA_6: '香川県その他',
    Area.EHIME_1: '愛媛県すべて',
    Area.EHIME_2: '松山・伊予',
    Area.EHIME_3: '今治・新居浜・西条',
    Area.EHIME_4: '大洲・八幡浜',
    Area.EHIME_5: '宇和島・西予',
    Area.EHIME_6: '愛媛県その他',
    Area.KOCHI_1: '高知県すべて',
    Area.KOCHI_2: '高知・南国・香南',
    Area.KOCHI_3: '安芸・室戸・香美',
    Area.KOCHI_4: '土佐・須崎',
    Area.KOCHI_5: '宿毛・四万十・土佐清水',
    Area.KOCHI_6: '高知県その他',
    Area.FUKUOKA_1: '福岡県すべて',
    Area.FUKUOKA_2: '天神・大名・今泉',
    Area.FUKUOKA_3: '警固・赤坂・大濠',
    Area.FUKUOKA_4: '博多・中州・住吉',
    Area.FUKUOKA_5: '渡辺通・薬院',
    Area.FUKUOKA_6: '平尾・高宮・大橋',
    Area.FUKUOKA_7: '六本松・別府・西新',
    Area.FUKUOKA_8: '井尻・南福岡・春日原',
    Area.FUKUOKA_9: '七隈・野芥・次郎丸',
    Area.FUKUOKA_10: '姪浜・筑前前原・九大学研都市',
    Area.FUKUOKA_11: '吉塚・箱崎・香椎',
    Area.FUKUOKA_12: '九産大・福津・糟屋郡',
    Area.FUKUOKA_13: '久留米・筑後',
    Area.FUKUOKA_14: '柳川・大川・大牟田',
    Area.FUKUOKA_15: '小倉・八幡・折尾',
    Area.FUKUOKA_16: '新宮・古賀',
    Area.FUKUOKA_17: '飯塚・田川',
    Area.SAGA_1: '佐賀県すべて',
    Area.SAGA_2: '佐賀・神埼・鳥栖',
    Area.SAGA_3: '唐津・伊万里',
    Area.SAGA_4: '武雄・多久・小城',
    Area.SAGA_5: '嬉野・鹿島',
    Area.SAGA_6: '佐賀県その他',
    Area.NAGASAKI_1: '長崎県すべて',
    Area.NAGASAKI_2: '長崎・西海',
    Area.NAGASAKI_3: '佐世保・平戸・松浦',
    Area.NAGASAKI_4: '雲仙・島原',
    Area.NAGASAKI_5: '諫早・大村',
    Area.NAGASAKI_6: '五島・壱岐・対馬',
    Area.NAGASAKI_7: '長崎県その他',
    Area.KUMAMOTO_1: '熊本県すべて',
    Area.KUMAMOTO_2: '熊本・宇土',
    Area.KUMAMOTO_3: '阿蘇',
    Area.KUMAMOTO_4: '菊池・山鹿',
    Area.KUMAMOTO_5: '荒尾・玉名',
    Area.KUMAMOTO_6: '八代・水俣・人吉',
    Area.KUMAMOTO_7: '熊本県その他',
    Area.OITA_1: '大分県すべて',
    Area.OITA_2: '大分・竹田・臼杵',
    Area.OITA_3: '別府・由布',
    Area.OITA_4: '国東・豊後高田・杵築',
    Area.OITA_5: '中津・宇佐・日田',
    Area.OITA_6: '佐伯',
    Area.MIYAZAKI_1: '宮崎県すべて',
    Area.MIYAZAKI_2: '宮崎市',
    Area.MIYAZAKI_3: '日南・串間',
    Area.MIYAZAKI_4: '都城・えびの・小林',
    Area.MIYAZAKI_5: '西都・日向',
    Area.MIYAZAKI_6: '延岡・高千穂',
    Area.MIYAZAKI_7: '宮崎県その他',
    Area.KAGOSHIMA_1: '鹿児島県すべて',
    Area.KAGOSHIMA_2: '鹿児島・南さつま',
    Area.KAGOSHIMA_3: '薩摩川内・出水・阿久根',
    Area.KAGOSHIMA_4: '伊佐・霧島・姶良',
    Area.KAGOSHIMA_5: '大隅半島',
    Area.KAGOSHIMA_6: '鹿児島県その他',
    Area.OKINAWA_1: '沖縄県すべて',
    Area.OKINAWA_2: '那覇・浦添',
    Area.OKINAWA_3: '沖縄・うるま・宜野湾',
    Area.OKINAWA_4: '名護市',
    Area.OKINAWA_5: '豊見城・糸満・南城',
    Area.OKINAWA_6: '沖縄県その他',
  };

  String get name => names[this] ?? '';

  String get value => toString().split('.').last;

  /// 会員ステータスにあたる文字列（ローマ字）からenumを生成する
  ///
  /// マッチしない場合は未選択を返す
  ///
  /// [value]: 'HOKKAIDO_1', 'HOKKAIDO_2' ...
  static Area from(String value) =>
      Area.values.firstWhere((e) => e.value == value);
}
